Add error handling to Scheduler
Sage-Bionetworks/mtb pull request #159
Opened 2021-05-25 23:53 UTC by leonli33

This is how the errors look:
![Screen Shot 2021-05-25 at 4 51 56 PM](https://user-images.githubusercontent.com/31671708/119582524-87aebb80-bd79-11eb-92a4-4e8e69680afd.png)

2021-05-25 23:55 UTC, leonli33 commented on src/components/studies/scheduler/AssessmentWindow.tsx
> +      className={clsx(classes.root, errorText && classes.redBorder)}
This is the only thing I added to the component.

2021-05-25 23:57 UTC, leonli33 commented on src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx
> +      {sessionErrorState && sessionErrorState.generalErrorMessage.length > 0 && (
Added error display here

2021-05-25 23:58 UTC, leonli33 commented on src/components/studies/scheduler/SchedulableSingleSessionContainer.tsx
> +          {windowErrors.length > 0 && (
Added error display here

2021-05-26 16:11 UTC, conundrumgirl requested changes

2021-05-26 16:11 UTC, conundrumgirl commented on src/components/studies/StudyBuilder.tsx
> +  const [schedulerError, setSchedulerError] = React.useState<string[]>([])
do you need a separate schedulerError? Can you just use error? When the scheduler is displayed all the errors will be the scheduler error. You can change the code around the ln 383 and check the section and don't display the errors the the studybuilder if the the section is scheduler

2021-05-26 16:11 UTC, conundrumgirl commented on src/components/studies/StudyBuilder.tsx
> +      console.log(e, 'error')
I think this logic should happen in the scheduler component. Just set the error and move this logic in the scheduler. 
The reasons for that are that:
a. this logic scheduler specific
b. you end up parsing the errors twice: - first time here and the second time in the scheduler

2021-05-27 22:39 UTC, conundrumgirl reviewed
let's merge it and see what breaks:)

2021-05-28 17:41 UTC, merged